# Generated by Django 5.2 on 2025-04-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('weekly_offer', models.BooleanField(default=False)),
                ('discounted', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='perfume_photos/')),
            ],
        ),
    ]
