# Generated by Django 5.2 on 2025-04-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='delivery_location',
            field=models.CharField(default='Countrywide', max_length=200),
        ),
        migrations.AddField(
            model_name='perfume',
            name='delivery_method',
            field=models.CharField(choices=[('free', 'Free Delivery'), ('pickup', 'Pick Up Mtaani'), ('paid', 'Paid Delivery')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='email',
            field=models.EmailField(default='your_email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='perfume',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfume',
            name='payment_on_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfume_photos/')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.perfume')),
            ],
        ),
    ]
