# Generated by Django 5.2 on 2025-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_perfume_contact_alter_perfume_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
