# Generated by Django 5.2 on 2025-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_perfume_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_photos/'),
        ),
    ]
